<?php

/**
 * Warehouse address list of Pilibaba
 */
return array(
    array(
        'country' => 'USA',
        'country_code' => 'US',
        'firstName' => 'JXPNC',
        'lastName' => 'Pilibaba',
        'address' => '70 McCullough Dr #Z0367',
        'city' => 'New Castle',
        'state' => 'DE (DELAWARE )',
        'zipcode' => '19720',
        'tel' => '302-604-5010',
    ),
    array(
        "country" => "Australia",
        "country_code" => "AU",
        "firstName" => "JXPNC",
        "lastName" => "Pilibaba",
        "address" => "96-100 Beaconsfield St., Silverwater #Z0367",
        "city" => "Sydney",
        "state" => "New South Wales",
        "zipcode" => "2128",
        "tel" => "2-96484237",
    ),
    array(
        "country" => "Germany",
        "country_code" => "DE",
        "firstName" => "Postfach JXPNC",
        "lastName" => "c/o Zebra Logistics GmbH",
        "address" => "Nordersand 1， #Z0367",
        "city" => "Hamburg",
        "state" => "Hamburg",
        "zipcode" => "20457",
        "tel" => "040-57130336",
    ),
    array(
        "country" => "Great Britain",
        "country_code" => "GB",
        "firstName" => "JXPNC",
        "lastName" => "Pilibaba",
        "address" => "Unit 13,Trident Way,Southall,London, #Z0367",
        "city" => "Southall",
        "state" => "GREATER LONDON",
        "zipcode" => "UB2 5LF",
        "tel" => "44 (020) 8571 0218",
    ),
    array(
        "country" => "HongKong",
        "country_code" => "HK",
        "firstName" => "JXPNC",
        "lastName" => "c/o AAE-HK",
        "address" => "FACTORY UNIT A ON 9/F, YOUNG YA INDUSTRIAL BUILDING, NOS. 381-389, SHA TSUI ROAD, TSUEN WAN,, NEW TERRITORIES, HONG KONG",
        "city" => "Hong Kong",
        "state" => "Hong Kong",
        "tel" => "852-39568542",
    ),
    array(
        "country" => "South Korea",
        "country_code" => "KR",
        "firstName" => "JXPNC",
        "lastName" => "Pilibaba",
        "address" => "1F,1348-1,Gonghang-dong #Z0367",
        "city" => "Gangseo-gu",
        "state" => "Seoul",
        "zipcode" => "157-816",
        "tel" => "02-444-9595",
    ),
    array(
        "country" => "Japan",
        "country_code" => "JP",
        "firstName" => "JXPNC",
        "lastName" => "Pilibaba",
        "address" => "大阪府和泉市のぞみ野3丁目1189番地36 #Z0367",
        "city" => "大阪",
        "state" => "大阪府",
        "zipcode" => "594-1105",
        "tel" => "072-558-7188",
    ),
    array(
        "country" => "China",
        "country_code" => "CN",
        "firstName" => "Pilibaba",
        "lastName" => "Pilibaba",
        "address" => "Room I, 9F No.288 South ZhongShan Rd",
        "city" => "Nanjing",
        "state" => "JiangSu",
        "zipcode" => "210005",
        "tel" => "86-25853-25853",
    ),
);

